### ISSUE TITLE
Exception raised when creating API keys

### ISSUE THREAD

**Issue by vtasca** [Polymarket/py-clob-client#38]
## Overview
There seems to be an issue with the `create_api_key()` method of the client object, it keeps throwing exceptions even though everything is initialized correctly.

## Description
The initial setup is straightforward and follows the examples in this repo:
```python
import os
from dotenv import load_dotenv
load_dotenv()
from py_clob_client.client import ClobClient
from py_clob_client.constants import POLYGON, MUMBAI

host = 'https://clob.polymarket.com/'
key = os.getenv('PRIVATE_KEY')  # as exported from Magic wallet
```

Then, the client is initialized correctly:
```python
client_1 = ClobClient(host, key=key, chain_id=MUMBAI)
```

However, upon attempting to create an API key, this is returned:
```python
creds = client_1.create_api_key()
```
```python
PolyApiException                       Traceback (most recent call last)
Cell In[101], line 1
----> 1 creds = client_1.create_api_key()

File ~\Documents\RP\repos\poly\venv\lib\site-packages\py_clob_client\client.py:128, in ClobClient.create_api_key(self, nonce)
    125 endpoint = "{}{}".format(self.host, CREATE_API_KEY)
    126 headers = create_level_1_headers(self.signer, nonce)
--> 128 creds = post(endpoint, headers=headers)
    129 self.logger.info(creds)
    130 return creds

File ~\Documents\RP\repos\poly\venv\lib\site-packages\py_clob_client\http_helpers\helpers.py:26, in post(endpoint, headers, data)
     25 def post(endpoint, headers=None, data=None):
---> 26     return request(endpoint, POST, headers, data)

File ~\Documents\RP\repos\poly\venv\lib\site-packages\py_clob_client\http_helpers\helpers.py:19, in request(endpoint, method, headers, data)
     15     resp = requests.request(
     16         method=method, url=endpoint, headers=headers, json=data if data else None
     17     )
     18     if resp.status_code != 200:
---> 19         raise PolyApiException(resp)
     20     return resp.json()
     21 except requests.RequestException:

PolyApiException: PolyApiException[status_code=400, error_message={'error': 'Invalid L1 Request headers'}]
```

Which doesn't make a lot of sense since the variables comprising the headers are set correctly, namely the private key, the host and the chain_id. I can verify this by calling `client_1.get_address()` which returns my public key.

## Notes
If it helps, when changing the `chain_id` to `POLYGON`, the returned error message changes:
```python
PolyApiException: PolyApiException[status_code=400, error_message={'error': 'Could not create api key'}]
```
I'm running Python 3.9.13.

## Action items

- [ ] Tag issue (bug, enhancement, feature, etc.)
- [ ] Initial discussion/assign team member
- [ ] Move discussion to PR if necessary and when ready

**Comment by JonathanAmenechi** [comment]
have you previously created an API key for the same address and nonce? You can check this by calling `get_api_keys`

**Comment by vtasca** [comment]
I have not - calling that method throws this exception:
```python
PolyException: API Credentials are needed to interact with this endpoint!
```

**Comment by JonathanAmenechi** [comment]
I see, try calling `derive_api_keys`. Since you exported the PK from Magic, then most likely an API key was already created when using the polymarket dot com website.

You can either use the same api keys you will receive from `derive_api_keys` or you can generate a new api key with a new nonce: e.g `client.create_api_key(nonce=1)`
