### ISSUE TITLE
Broken on Python3.11 due to deprecated dependency `pysha3`

### ISSUE THREAD

**Issue by mvanaltvorst** [Polymarket/py-clob-client#65]
## Overview

`pysha3` has been deprecated and is not supported anymore. This also means that the install fails on Python 3.11.

**Comment by chenr1** [comment]
My only solution here was to use a Conda environment on the older version.

**Comment by JonathanAmenechi** [comment]
Fixed by https://github.com/Polymarket/py-clob-client/pull/85
