### ISSUE TITLE
Bug: Signing Signature type 1 not possible (status 400)

### ISSUE THREAD

**Issue by cmp-nct** [Polymarket/py-clob-client#94]
I've split this one out of my questions from yesterday.

When using signature type 1 I get a correct allowance/balance from my polymarket (created by PM) wallet, however the post_order() call returns error 400.
```
Traceback (most recent call last):
  File "/root/polymarket/pythonProject/tool_create_order.py", line 115, in <module>
    resp = client.post_order(signed_order, OrderType.GTD)
  File "/usr/local/lib/python3.10/site-packages/py_clob_client/client.py", line 420, in post_order
    return post("{}{}".format(self.host, POST_ORDER), headers=headers, data=body)
  File "/usr/local/lib/python3.10/site-packages/py_clob_client/http_helpers/helpers.py", line 54, in post
    return request(endpoint, POST, headers, data)
  File "/usr/local/lib/python3.10/site-packages/py_clob_client/http_helpers/helpers.py", line 42, in request
    raise PolyApiException(resp)
py_clob_client.exceptions.PolyApiException: PolyApiException[status_code=400, error_message={'error': 'invalid signature'}] 
```

I've tried various changes, any examples I could find. Tried adding/removing the hex identifier 0x. Nothing I do works.
However, when using another signature type I get "no allowance" as result, so I assume the signature was read OK in those cases ?

```
# client = ClobClient(host, key=PK, chain_id=chain_id, creds=credentials, signature_type=1, funder="0x"+funder)
client = ClobClient(host, key=PK, chain_id=chain_id, signature_type=1)
client.set_api_creds(client.create_or_derive_api_creds())
```

I've found no actual example on google or here that uses the PM created wallet, am I doing something wrong or is it just very unusual to use the Polymaker default wallet ?

**Comment by 10ucapital** [comment]
Hi, how did you solve? I met exactly same problem. 

L1 ok to get balance, but cannot post order.

**Comment by kkwezard** [comment]
@cmp-nct Have you solved this issue? I've got the same problem，I initialized client using signature type 1 and do some getting market API successfully but failed to do post_order calling. It always returns "invalid signature" error.
