### ISSUE TITLE
No information on how to increase allowance

### ISSUE THREAD

**Issue by vegardkd** [Polymarket/py-clob-client#95]
When trading with the py client, there will be an error saying not enough balance / allowance for sums like 600 usdc, but 5 usdc is fine. It seems this has to do with the allowance limit. Are there any docs on how to increase/decrease it?

**Comment by ArnaudBernaille** [comment]
Same issue

**Comment by hsz0403** [comment]
same here. any solutions?

**Comment by fshabashev** [comment]
https://gist.github.com/poly-rodr/44313920481de58d5a3f6d1f8226bd5e

they have this code to increase allowance. 
I can see that the allowance has increased for me, however the balance stays 0, no idea why.

**Comment by prod-ric** [comment]
Same here

> Same issue.
> 
> When I check my allowance:
> 
> ```
> params = BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
> allowance = client.get_balance_allowance(params)
> ```
> 
> In the response, I see 0 for all the tokens. I do have USDC in my account. Maybe they only consider other coins...

**Comment by xakbel** [comment]
> https://gist.github.com/poly-rodr/44313920481de58d5a3f6d1f8226bd5e
> 
> they have this code to increase allowance. I can see that the allowance has increased for me, however the balance stays 0, no idea why.

Same problem. Still 0. Any help?

**Comment by joachim23344** [comment]
I also have the same problem has this been solved already?

**Comment by dineshtiwari69** [comment]
Not sure if this helps , but i had similar issue with balance and allowances showing 0 despite using 
 I managed to solve it by adding funder and signature_type arg in client init 
 
`
clob_client.update_balance_allowance(
                params=BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
        )
`
        
 `clob_client = ClobClient(host, key=key, chain_id=chain_id,funder=address,signature_type=1)`

**Comment by Stepka** [comment]
> Same issue.
> 
> When I check my allowance:
> 
> ```
> params = BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
> allowance = client.get_balance_allowance(params)
> ```
> 
> In the response, I see 0 for all the tokens. I do have USDC in my account. Maybe they only consider other coins...

They show `USDC.e` token instead `USDC`
